version: "3"

services:
  node:
    
    image: node:16

    container_name: normalized
  
    tty: true
  
    stdin_open: true
  
    command: bash
    
    restart: always
    
    working_dir: /app
   
    volumes:
     
     
      - ./:/app
   
    depends_on:
     
      - db
   
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOSTNAME: db
      MYSQL_PORT: 3306


  db:
    container_name: normalized_db
    image: mysql:8.0.23
    restart: always
  
    ports:

      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password


networks:

  default:
    name: normalized_net
